#ifndef AR_PERFORCERESOLVER_API_H
#define AR_PERFORCERESOLVER_API_H

#include "pxr/base/arch/export.h"

#if defined(PXR_STATIC)
#   define AR_PERFORCERESOLVER_API
#   define AR_PERFORCERESOLVER_API_TEMPLATE_CLASS(...)
#   define AR_PERFORCERESOLVER_API_TEMPLATE_STRUCT(...)
#   define AR_PERFORCERESOLVER_LOCAL
#else
#   if defined(AR_PERFORCERESOLVER_EXPORTS)
#       define AR_PERFORCERESOLVER_API ARCH_EXPORT
#       define AR_PERFORCERESOLVER_API_TEMPLATE_CLASS(...) ARCH_EXPORT_TEMPLATE(class, __VA_ARGS__)
#       define AR_PERFORCERESOLVER_API_TEMPLATE_STRUCT(...) ARCH_EXPORT_TEMPLATE(struct, __VA_ARGS__)
#   else
#       define AR_PERFORCERESOLVER_API ARCH_IMPORT
#       define AR_PERFORCERESOLVER_API_TEMPLATE_CLASS(...) ARCH_IMPORT_TEMPLATE(class, __VA_ARGS__)
#       define AR_PERFORCERESOLVER_API_TEMPLATE_STRUCT(...) ARCH_IMPORT_TEMPLATE(struct, __VA_ARGS__)
#   endif
#   define AR_PERFORCERESOLVER_LOCAL ARCH_HIDDEN
#endif

#endif // AR_PERFORCERESOLVER_API_H
