#ifndef AR_PERFORCERESOLVER_DEBUGCODES_H
#define AR_PERFORCERESOLVER_DEBUGCODES_H

#include <pxr/pxr.h>
#include "pxr/base/tf/debug.h"

PXR_NAMESPACE_OPEN_SCOPE

TF_DEBUG_CODES(
    PERFORCE_RESOLVER,
    PERFORCE_CLIENT
);

PXR_NAMESPACE_CLOSE_SCOPE

#endif // AR_PERFORCERESOLVER_DEBUGCODES_H